META_ARC: "SiamIRCA"

BACKBONE:
    TYPE: "resnet50"
    KWARGS:
        used_layers: [2, 3, 4]
    PRETRAINED: ''
    TRAIN_LAYERS: ['layer2', 'layer3', 'layer4']
    TRAIN_EPOCH: 10
    LAYERS_LR: 0.1

ADJUST:
    ADJUST: True
    TYPE: "AdjustAllLayer"
    KWARGS:
        in_channels: [512, 1024, 2048]
        out_channels: [256, 256, 256]

IRCA:
    IRCA: True
    TYPE: 'MultiIRCA'
    KWARGS:
        cls_out_channels: 2  # if use sigmoid cls, cls_out_channel = 1 else 2

POINT:
    STRIDE: 8

TRACK:
    TYPE: 'SiamIRCATracker'
    WINDOW_INFLUENCE: 0.50508504812909971  # VOT2018
    PENALTY_K: 0.18102710080065654  # VOT2018
    LR: 0.42514553079630213  # VOT2018
#    WINDOW_INFLUENCE: 0.54173081840727733  # OTB100
#    PENALTY_K: 0.2671318082139889  # OTB100
#    LR: 0.71989091192643584  # OTB100
#    WINDOW_INFLUENCE: 0.06892146013614994 # LaSOT
#    PENALTY_K: 0.01674825284081131  # LaSOT
#    LR: 0.39330148152719768 # LaSOT
#    WINDOW_INFLUENCE: 0.06047256927432828  # GOT-10K
#    PENALTY_K: 0.04867851571852032  # GOT-10K
#    LR: 0.75605887925043103  # GOT-10K
#    WINDOW_INFLUENCE: 0.334450048565355  # TrackingNet
#    PENALTY_K: 0.0012159181005195463  # TrackingNet
#    LR: 0.46386814967815493  # TrackingNet
    EXEMPLAR_SIZE: 127
    INSTANCE_SIZE: 255
    BASE_SIZE: 8
    CONTEXT_AMOUNT: 0.5

TRAIN:
    EPOCH: 20
    START_EPOCH: 0 # 0 or resume checkpoint
    BATCH_SIZE: 28
    BASE_LR: 0.005
    CLS_WEIGHT: 1.0
    LOC_WEIGHT: 1.0
    RESUME: '' # '' or 'snapshot/checkpoint_e.pth'

    LR:
        TYPE: 'log'
        KWARGS:
            start_lr: 0.005
            end_lr: 0.00005
    LR_WARMUP:
        TYPE: 'step'
        EPOCH: 5
        KWARGS:
            start_lr: 0.001
            end_lr: 0.005
            step: 1

DATASET:
    NAMES:
    - 'VID'
    - 'YOUTUBEBB'
    - 'COCO'
    - 'DET'
    - 'GOT10K'
    - 'LASOT'

    VIDEOS_PER_EPOCH: 1000000

    TEMPLATE:
        SHIFT: 4
        SCALE: 0.05
        BLUR: 0.0
        FLIP: 0.0
        COLOR: 1.0

    SEARCH:
        SHIFT: 64
        SCALE: 0.18
        BLUR: 0.2
        FLIP: 0.0
        COLOR: 1.0

    NEG: 0.2
    GRAY: 0.0
